// 中学2年生・2学期 中間試験を想定した仮の出題データです。
// 実際の教科書・試験範囲に合わせて、このファイルの中身を書きかえてください。
// word: 英単語 / reading: カタカナ読み(耳で覚える用) / meaning: 日本語の意味
// example: 例文 / exampleJa: 例文の日本語訳

export type VocabWord = {
  id: string;
  word: string;
  reading: string;
  meaning: string;
  example: string;
  exampleJa: string;
};

export const vocabList: VocabWord[] = [
  { id: "v1", word: "yesterday", reading: "イェスタデイ", meaning: "きのう", example: "I watched TV yesterday.", exampleJa: "私はきのうテレビを見ました。" },
  { id: "v2", word: "tomorrow", reading: "トゥモロー", meaning: "あした", example: "See you tomorrow.", exampleJa: "またあした会いましょう。" },
  { id: "v3", word: "already", reading: "オールレディ", meaning: "すでに、もう", example: "I have already finished my homework.", exampleJa: "私はもう宿題を終えました。" },
  { id: "v4", word: "famous", reading: "フェイマス", meaning: "有名な", example: "She is a famous singer.", exampleJa: "彼女は有名な歌手です。" },
  { id: "v5", word: "difficult", reading: "ディフィカルト", meaning: "難しい", example: "This question is difficult.", exampleJa: "この問題は難しいです。" },
  { id: "v6", word: "important", reading: "インポータント", meaning: "大切な、重要な", example: "Water is important for life.", exampleJa: "水は生きるために大切です。" },
  { id: "v7", word: "history", reading: "ヒストリー", meaning: "歴史", example: "I like Japanese history.", exampleJa: "私は日本の歴史が好きです。" },
  { id: "v8", word: "culture", reading: "カルチャー", meaning: "文化", example: "Kyoto has a long culture.", exampleJa: "京都には長い歴史を持つ文化があります。" },
  { id: "v9", word: "traditional", reading: "トラディショナル", meaning: "伝統的な", example: "This is a traditional festival.", exampleJa: "これは伝統的なお祭りです。" },
  { id: "v10", word: "abroad", reading: "アブロード", meaning: "海外へ、外国で", example: "I want to study abroad.", exampleJa: "私は海外で勉強したいです。" },
  { id: "v11", word: "decide", reading: "ディサイド", meaning: "決める", example: "I decided to join the club.", exampleJa: "私はその部活に入ることに決めました。" },
  { id: "v12", word: "become", reading: "ビカム", meaning: "〜になる", example: "I want to become a doctor.", exampleJa: "私は医者になりたいです。" },
  { id: "v13", word: "each other", reading: "イーチアザー", meaning: "お互いに", example: "We helped each other.", exampleJa: "私たちはお互いに助け合いました。" },
  { id: "v14", word: "several", reading: "セベラル", meaning: "いくつかの", example: "I have several pens.", exampleJa: "私はいくつかのペンを持っています。" },
  { id: "v15", word: "probably", reading: "プロバブリー", meaning: "たぶん", example: "It will probably rain tomorrow.", exampleJa: "あしたはたぶん雨が降るでしょう。" },
  { id: "v16", word: "improve", reading: "インプルーブ", meaning: "上達させる、改善する", example: "I want to improve my English.", exampleJa: "私は英語を上達させたいです。" },
  { id: "v17", word: "environment", reading: "インバイロメント", meaning: "環境", example: "We must protect the environment.", exampleJa: "私たちは環境を守らなければなりません。" },
  { id: "v18", word: "planet", reading: "プラネット", meaning: "惑星", example: "The earth is a planet.", exampleJa: "地球は惑星です。" },
  { id: "v19", word: "space", reading: "スペイス", meaning: "宇宙", example: "He wants to go to space.", exampleJa: "彼は宇宙に行きたいと思っています。" },
  { id: "v20", word: "scientist", reading: "サイエンティスト", meaning: "科学者", example: "She is a great scientist.", exampleJa: "彼女はすばらしい科学者です。" },
  { id: "v21", word: "invention", reading: "インベンション", meaning: "発明", example: "The internet is a great invention.", exampleJa: "インターネットはすばらしい発明です。" },
  { id: "v22", word: "borrow", reading: "バロー", meaning: "借りる", example: "Can I borrow your pen?", exampleJa: "あなたのペンを借りてもいいですか。" },
  { id: "v23", word: "lend", reading: "レンド", meaning: "貸す", example: "Can you lend me your book?", exampleJa: "あなたの本を貸してくれますか。" },
  { id: "v24", word: "arrive", reading: "アライブ", meaning: "到着する", example: "We arrived at the station at six.", exampleJa: "私たちは6時に駅に着きました。" },
  { id: "v25", word: "either", reading: "イーザー", meaning: "どちらか、〜も(否定文で)", example: "I don't like coffee, either.", exampleJa: "私もコーヒーが好きではありません。" },
  { id: "v26", word: "several times", reading: "セベラルタイムズ", meaning: "何度か", example: "I have visited Kyoto several times.", exampleJa: "私は何度か京都を訪れたことがあります。" },
  { id: "v27", word: "twice", reading: "トゥワイス", meaning: "2回", example: "I have been there twice.", exampleJa: "私はそこに2回行ったことがあります。" },
  { id: "v28", word: "wonderful", reading: "ワンダフル", meaning: "すばらしい", example: "We had a wonderful time.", exampleJa: "私たちはすばらしい時間を過ごしました。" },
  { id: "v29", word: "popular", reading: "ポピュラー", meaning: "人気のある", example: "This song is popular.", exampleJa: "この歌は人気があります。" },
  { id: "v30", word: "expensive", reading: "エクスペンシブ", meaning: "値段が高い", example: "This bag is very expensive.", exampleJa: "このバッグはとても値段が高いです。" },
  { id: "v31", word: "cheap", reading: "チープ", meaning: "安い", example: "This shop is cheap.", exampleJa: "この店は安いです。" },
  { id: "v32", word: "convenient", reading: "コンビーニエント", meaning: "便利な", example: "This app is very convenient.", exampleJa: "このアプリはとても便利です。" },
  { id: "v33", word: "purpose", reading: "パーパス", meaning: "目的", example: "What is the purpose of your trip?", exampleJa: "あなたの旅行の目的は何ですか。" },
  { id: "v34", word: "future", reading: "フューチャー", meaning: "未来、将来", example: "I think about my future.", exampleJa: "私は自分の将来について考えます。" },
  { id: "v35", word: "dream", reading: "ドリーム", meaning: "夢", example: "My dream is to be a teacher.", exampleJa: "私の夢は先生になることです。" },
  { id: "v36", word: "goal", reading: "ゴール", meaning: "目標", example: "Our goal is to win the game.", exampleJa: "私たちの目標は試合に勝つことです。" },
  { id: "v37", word: "language", reading: "ラングウィッジ", meaning: "言語", example: "English is an important language.", exampleJa: "英語は大切な言語です。" },
  { id: "v38", word: "foreign", reading: "フォーリン", meaning: "外国の", example: "I want to visit a foreign country.", exampleJa: "私は外国を訪れたいです。" },
  { id: "v39", word: "opinion", reading: "オピニオン", meaning: "意見", example: "What is your opinion about this?", exampleJa: "これについてのあなたの意見は何ですか。" },
  { id: "v40", word: "experience", reading: "イクスピリエンス", meaning: "経験", example: "That was a great experience.", exampleJa: "それはすばらしい経験でした。" },
  { id: "v41", word: "introduce", reading: "イントロデュース", meaning: "紹介する", example: "Let me introduce myself.", exampleJa: "自己紹介させてください。" },
  { id: "v42", word: "research", reading: "リサーチ", meaning: "研究、調べること", example: "She did research about animals.", exampleJa: "彼女は動物について研究しました。" },
  { id: "v43", word: "volunteer", reading: "ボランティア", meaning: "ボランティア", example: "He works as a volunteer.", exampleJa: "彼はボランティアとして働いています。" },
  { id: "v44", word: "graduate", reading: "グラジュエイト", meaning: "卒業する", example: "I will graduate next year.", exampleJa: "私は来年卒業します。" },
];

export type GrammarQuestion = {
  id: string;
  prompt: string; // 日本語での問題文
  sentence: string; // ___ を含む英文
  sentenceJa: string; // 完成した英文の日本語訳
  answer: string; // 正解(小文字/大文字はゆるく判定)
  hint: string;
};

export const grammarList: GrammarQuestion[] = [
  {
    id: "g1",
    prompt: "( )の動詞を過去形にしよう",
    sentence: "I ___ (play) tennis last Sunday.",
    sentenceJa: "私はこの前の日曜日にテニスをしました。",
    answer: "played",
    hint: "規則動詞は ed をつける",
  },
  {
    id: "g2",
    prompt: "( )の動詞を過去形にしよう(不規則動詞)",
    sentence: "She ___ (go) to Osaka last week.",
    sentenceJa: "彼女は先週大阪に行きました。",
    answer: "went",
    hint: "go の過去形は特別な形",
  },
  {
    id: "g3",
    prompt: "( )の動詞を過去形にしよう",
    sentence: "We ___ (see) a movie yesterday.",
    sentenceJa: "私たちはきのう映画を見ました。",
    answer: "saw",
    hint: "see の過去形",
  },
  {
    id: "g4",
    prompt: "( )の形容詞を比較級にしよう",
    sentence: "This book is ___ (interesting) than that one.",
    sentenceJa: "この本はあの本よりおもしろいです。",
    answer: "more interesting",
    hint: "長い形容詞は more をつける",
  },
  {
    id: "g5",
    prompt: "( )の形容詞を比較級にしよう",
    sentence: "Tom is ___ (tall) than Ken.",
    sentenceJa: "トムはケンより背が高いです。",
    answer: "taller",
    hint: "短い形容詞は er をつける",
  },
  {
    id: "g6",
    prompt: "( )の形容詞を最上級にしよう",
    sentence: "This is the ___ (famous) temple in Kyoto.",
    sentenceJa: "これは京都で最も有名なお寺です。",
    answer: "most famous",
    hint: "長い形容詞は most をつける",
  },
  {
    id: "g7",
    prompt: "( )の形容詞を最上級にしよう",
    sentence: "Mt. Fuji is the ___ (high) mountain in Japan.",
    sentenceJa: "富士山は日本で最も高い山です。",
    answer: "highest",
    hint: "短い形容詞は est をつける",
  },
  {
    id: "g8",
    prompt: "There is / There are の文を完成させよう",
    sentence: "___ a cat under the table.",
    sentenceJa: "テーブルの下にねこが1匹います。",
    answer: "there is",
    hint: "単数のときは is",
  },
  {
    id: "g9",
    prompt: "There is / There are の文を完成させよう",
    sentence: "___ many students in the gym.",
    sentenceJa: "体育館にたくさんの生徒がいます。",
    answer: "there are",
    hint: "複数のときは are",
  },
  {
    id: "g10",
    prompt: "「〜すること」の形(不定詞)を完成させよう",
    sentence: "I want ___ (study) English.",
    sentenceJa: "私は英語を勉強したいです。",
    answer: "to study",
    hint: "want to + 動詞の原形",
  },
  {
    id: "g11",
    prompt: "「〜するために」の形(不定詞・目的)を完成させよう",
    sentence: "He went to the library ___ (read) books.",
    sentenceJa: "彼は本を読むために図書館へ行きました。",
    answer: "to read",
    hint: "目的を表す to + 動詞の原形",
  },
  {
    id: "g12",
    prompt: "「〜すべきこと」の形を完成させよう",
    sentence: "I have a lot of things ___ (do) today.",
    sentenceJa: "私には今日やるべきことがたくさんあります。",
    answer: "to do",
    hint: "名詞を後ろから修飾する to + 動詞の原形",
  },
  {
    id: "g13",
    prompt: "現在完了形(経験)の文を完成させよう",
    sentence: "I ___ (visit) Kyoto twice.",
    sentenceJa: "私は京都を2回訪れたことがあります。",
    answer: "have visited",
    hint: "have + 過去分詞",
  },
  {
    id: "g14",
    prompt: "現在完了形(完了)の文を完成させよう",
    sentence: "She ___ (finish) her homework already.",
    sentenceJa: "彼女はもう宿題を終えました。",
    answer: "has finished",
    hint: "主語が3人称単数なら has",
  },
  {
    id: "g15",
    prompt: "「〜しなければならない」の文を完成させよう",
    sentence: "You ___ (must) study hard for the test.",
    sentenceJa: "あなたはテストのために一生懸命勉強しなければなりません。",
    answer: "must",
    hint: "そのままの形でOK",
  },
  {
    id: "g16",
    prompt: "「〜する必要がある」の文を完成させよう",
    sentence: "We ___ (have to) leave now.",
    sentenceJa: "私たちは今出発しなければなりません。",
    answer: "have to",
    hint: "主語がwe/youなら have to",
  },
  {
    id: "g17",
    prompt: "「〜されている」受け身の文を完成させよう",
    sentence: "English ___ (speak) in many countries.",
    sentenceJa: "英語は多くの国で話されています。",
    answer: "is spoken",
    hint: "be動詞 + 過去分詞",
  },
  {
    id: "g18",
    prompt: "「〜されている」受け身の文を完成させよう",
    sentence: "This song ___ (love) by many people.",
    sentenceJa: "この歌は多くの人に愛されています。",
    answer: "is loved",
    hint: "be動詞 + 過去分詞",
  },
  {
    id: "g19",
    prompt: "「〜することが好き」動名詞の文を完成させよう",
    sentence: "I like ___ (play) the guitar.",
    sentenceJa: "私はギターを弾くことが好きです。",
    answer: "playing",
    hint: "動詞のing形",
  },
  {
    id: "g20",
    prompt: "「〜し終える」動名詞の文を完成させよう",
    sentence: "I finished ___ (eat) breakfast.",
    sentenceJa: "私は朝食を食べ終えました。",
    answer: "eating",
    hint: "finish の後ろは ing形",
  },
  {
    id: "g21",
    prompt: "「〜できる」助動詞の文を完成させよう",
    sentence: "He ___ (can) swim very well.",
    sentenceJa: "彼はとても上手に泳ぐことができます。",
    answer: "can",
    hint: "「〜できる」= can",
  },
  {
    id: "g22",
    prompt: "「〜したほうがよい」助動詞の文を完成させよう",
    sentence: "You ___ (should) see a doctor.",
    sentenceJa: "あなたは医者に診てもらったほうがいいです。",
    answer: "should",
    hint: "「〜したほうがよい」= should",
  },
  {
    id: "g23",
    prompt: "「〜のとき」を表す接続詞を完成させよう",
    sentence: "___ (when) I was young, I lived in Tokyo.",
    sentenceJa: "私は若いとき、東京に住んでいました。",
    answer: "when",
    hint: "時を表す接続詞",
  },
  {
    id: "g24",
    prompt: "「なぜなら〜」を表す接続詞を完成させよう",
    sentence: "I was tired ___ (because) I did not sleep well.",
    sentenceJa: "私はよく眠れなかったので疲れていました。",
    answer: "because",
    hint: "理由を表す接続詞",
  },
  {
    id: "g25",
    prompt: "「もし〜ならば」を表す接続詞を完成させよう",
    sentence: "___ (if) it rains tomorrow, we will stay home.",
    sentenceJa: "もしあした雨が降ったら、私たちは家にいます。",
    answer: "if",
    hint: "条件を表す接続詞",
  },
  {
    id: "g26",
    prompt: "「〜することを楽しむ」動名詞の文を完成させよう",
    sentence: "I enjoy ___ (read) comic books.",
    sentenceJa: "私は漫画を読むことを楽しんでいます。",
    answer: "reading",
    hint: "enjoy の後ろは ing形",
  },
  {
    id: "g27",
    prompt: "「人に〜してほしい」の形を完成させよう",
    sentence: "My mother wants me ___ (clean) my room.",
    sentenceJa: "母は私に部屋を掃除してほしいと思っています。",
    answer: "to clean",
    hint: "want + 人 + to + 動詞の原形",
  },
  {
    id: "g28",
    prompt: "( )の動詞を主語に合わせて正しい形にしよう",
    sentence: "That cake ___ (look) delicious.",
    sentenceJa: "あのケーキはおいしそうに見えます。",
    answer: "looks",
    hint: "主語が3人称単数なら s をつける",
  },
  {
    id: "g29",
    prompt: "「〜しませんか」とさそう文を完成させよう",
    sentence: "Why don't we ___ (go) to the movies?",
    sentenceJa: "映画に行きませんか。",
    answer: "go",
    hint: "Why don't we + 動詞の原形",
  },
];
