// 中学3年生レベルを想定した出題データです。
// 実際の教科書・試験範囲に合わせて、このファイルの中身を書きかえてください。
// word: 英単語 / reading: カタカナ読み(耳で覚える用) / meaning: 日本語の意味
// example: 例文 / exampleJa: 例文の日本語訳

export type VocabWord = {
  id: string;
  word: string;
  reading: string;
  meaning: string;
  example: string;
  exampleJa: string;
};

export const vocabList: VocabWord[] = [
  { id: "v1", word: "solve", reading: "ソルブ", meaning: "解決する", example: "We need to solve this problem together.", exampleJa: "私たちはこの問題をいっしょに解決する必要があります。" },
  { id: "v2", word: "increase", reading: "インクリース", meaning: "増える、増やす", example: "The population may increase in the future.", exampleJa: "人口は将来増えるかもしれません。" },
  { id: "v3", word: "decrease", reading: "ディクリース", meaning: "減る、減らす", example: "We should decrease the amount of plastic waste.", exampleJa: "私たちはプラスチックごみの量を減らすべきです。" },
  { id: "v4", word: "average", reading: "アベレージ", meaning: "平均(の)", example: "The average temperature is rising.", exampleJa: "平均気温は上昇しています。" },
  { id: "v5", word: "society", reading: "ソサエティ", meaning: "社会", example: "Technology has changed our society a lot.", exampleJa: "科学技術は私たちの社会を大きく変えました。" },
  { id: "v6", word: "develop", reading: "ディベロップ", meaning: "発達させる、開発する", example: "Scientists are trying to develop new medicine.", exampleJa: "科学者たちは新しい薬を開発しようとしています。" },
  { id: "v7", word: "development", reading: "ディベロップメント", meaning: "発展、開発", example: "This town has a long history of development.", exampleJa: "この町には発展の長い歴史があります。" },
  { id: "v8", word: "technology", reading: "テクノロジー", meaning: "科学技術", example: "New technology can solve many problems.", exampleJa: "新しい科学技術は多くの問題を解決できます。" },
  { id: "v9", word: "pollution", reading: "ポリューション", meaning: "汚染", example: "Air pollution is a serious problem in some cities.", exampleJa: "大気汚染は一部の都市で深刻な問題です。" },
  { id: "v10", word: "recycle", reading: "リサイクル", meaning: "リサイクルする", example: "We should recycle paper and plastic bottles.", exampleJa: "私たちは紙やペットボトルをリサイクルするべきです。" },
  { id: "v11", word: "resources", reading: "リソーシズ", meaning: "資源", example: "We must use natural resources carefully.", exampleJa: "私たちは天然資源を大切に使わなければなりません。" },
  { id: "v12", word: "energy", reading: "エナジー", meaning: "エネルギー", example: "Solar energy is clean and safe.", exampleJa: "太陽エネルギーはクリーンで安全です。" },
  { id: "v13", word: "protect", reading: "プロテクト", meaning: "守る", example: "It is our job to protect the environment.", exampleJa: "環境を守ることは私たちの仕事です。" },
  { id: "v14", word: "climate", reading: "クライメット", meaning: "気候", example: "The climate of this country is very different from Japan's.", exampleJa: "この国の気候は日本の気候とはとても違います。" },
  { id: "v15", word: "disaster", reading: "ディザスター", meaning: "災害", example: "Many people lost their homes because of the disaster.", exampleJa: "多くの人々がその災害で家を失いました。" },
  { id: "v16", word: "support", reading: "サポート", meaning: "支え、支援する", example: "I always need my family's support.", exampleJa: "私はいつも家族の支えを必要としています。" },
  { id: "v17", word: "produce", reading: "プロデュース", meaning: "生産する", example: "This factory will produce more cars next year.", exampleJa: "この工場は来年もっと多くの車を生産するでしょう。" },
  { id: "v18", word: "products", reading: "プロダクツ", meaning: "製品", example: "This company makes high-quality products.", exampleJa: "この会社は質の高い製品を作っています。" },
  { id: "v19", word: "spread", reading: "スプレッド", meaning: "広がる、広める", example: "The news spread quickly around the world.", exampleJa: "そのニュースはあっという間に世界中に広まりました。" },
  { id: "v20", word: "reduce", reading: "リデュース", meaning: "減らす", example: "We need to reduce the amount of garbage.", exampleJa: "私たちはごみの量を減らす必要があります。" },
  { id: "v21", word: "amount", reading: "アマウント", meaning: "量", example: "A large amount of rain fell last night.", exampleJa: "きのうの夜、大量の雨が降りました。" },
  { id: "v22", word: "population", reading: "ポピュレーション", meaning: "人口", example: "The population of this city is growing fast.", exampleJa: "この都市の人口は急速に増えています。" },
  { id: "v23", word: "communicate", reading: "コミュニケイト", meaning: "意思を伝え合う", example: "We can communicate with people around the world easily now.", exampleJa: "私たちは今、世界中の人々と簡単に意思疎通ができます。" },
  { id: "v24", word: "communication", reading: "コミュニケーション", meaning: "意思疎通", example: "Good communication is important in a team.", exampleJa: "良いコミュニケーションはチームの中で大切です。" },
  { id: "v25", word: "connect", reading: "コネクト", meaning: "つなぐ", example: "The internet can connect people all over the world.", exampleJa: "インターネットは世界中の人々をつなぐことができます。" },
  { id: "v26", word: "relationship", reading: "リレーションシップ", meaning: "関係", example: "They have a good relationship with each other.", exampleJa: "彼らはお互いに良い関係を持っています。" },
  { id: "v27", word: "achieve", reading: "アチーブ", meaning: "達成する", example: "She worked hard to achieve her goal.", exampleJa: "彼女は自分の目標を達成するために一生懸命努力しました。" },
  { id: "v28", word: "challenge", reading: "チャレンジ", meaning: "課題、挑戦", example: "Learning a new language is a big challenge.", exampleJa: "新しい言語を学ぶことは大きな挑戦です。" },
  { id: "v29", word: "skills", reading: "スキルズ", meaning: "技能", example: "You can improve your skills through practice.", exampleJa: "練習を通して技能を向上させることができます。" },
  { id: "v30", word: "effort", reading: "エフォート", meaning: "努力", example: "Success needs a lot of effort.", exampleJa: "成功にはたくさんの努力が必要です。" },
  { id: "v31", word: "succeed", reading: "サクシード", meaning: "成功する", example: "He will succeed if he keeps trying.", exampleJa: "彼は努力を続ければ成功するでしょう。" },
  { id: "v32", word: "success", reading: "サクセス", meaning: "成功", example: "Her hard work led to great success.", exampleJa: "彼女の努力は大きな成功につながりました。" },
  { id: "v33", word: "fail", reading: "フェイル", meaning: "失敗する", example: "Don't be afraid to fail.", exampleJa: "失敗することを恐れないで。" },
  { id: "v34", word: "failure", reading: "フェイリャー", meaning: "失敗", example: "We can learn a lot from failure.", exampleJa: "私たちは失敗から多くのことを学べます。" },
  { id: "v35", word: "quality", reading: "クオリティ", meaning: "質", example: "This restaurant is known for its high quality food.", exampleJa: "このレストランは質の高い食事で知られています。" },
  { id: "v36", word: "quantity", reading: "クワンティティ", meaning: "量、数量", example: "We need a large quantity of water for this project.", exampleJa: "このプロジェクトには大量の水が必要です。" },
  { id: "v37", word: "various", reading: "ベアリアス", meaning: "さまざまな", example: "You can learn various things from books.", exampleJa: "本からさまざまなことを学ぶことができます。" },
  { id: "v38", word: "valuable", reading: "バリュアブル", meaning: "価値のある", example: "Time is more valuable than money.", exampleJa: "時間はお金よりも価値があります。" },
  { id: "v39", word: "necessary", reading: "ネセサリー", meaning: "必要な", example: "It is necessary to protect our environment.", exampleJa: "私たちの環境を守ることは必要です。" },
  { id: "v40", word: "possible", reading: "ポシブル", meaning: "可能な", example: "Is it possible to finish this work by tomorrow?", exampleJa: "この仕事をあしたまでに終わらせることは可能ですか。" },
  { id: "v41", word: "impossible", reading: "インポシブル", meaning: "不可能な", example: "Nothing is impossible if you try your best.", exampleJa: "全力を尽くせば不可能なことは何もありません。" },
  { id: "v42", word: "modern", reading: "モダン", meaning: "現代の", example: "This building has a very modern design.", exampleJa: "この建物はとても現代的なデザインです。" },
  { id: "v43", word: "traditional", reading: "トラディショナル", meaning: "伝統的な", example: "This festival keeps a traditional custom.", exampleJa: "この祭りは伝統的な習慣を守っています。" },
  { id: "v44", word: "positive", reading: "ポジティブ", meaning: "前向きな", example: "Try to have a positive attitude.", exampleJa: "前向きな姿勢を持つようにしてください。" },
  { id: "v45", word: "negative", reading: "ネガティブ", meaning: "否定的な", example: "Too much negative thinking can make you tired.", exampleJa: "あまりに否定的に考えすぎると疲れてしまいます。" },
  { id: "v46", word: "equal", reading: "イコール", meaning: "平等な", example: "Everyone should have equal opportunities.", exampleJa: "誰もが平等な機会を持つべきです。" },
  { id: "v47", word: "respect", reading: "リスペクト", meaning: "尊敬する、尊重する", example: "We should respect different cultures.", exampleJa: "私たちは異なる文化を尊重すべきです。" },
  { id: "v48", word: "imagine", reading: "イマジン", meaning: "想像する", example: "Can you imagine a life without smartphones?", exampleJa: "スマートフォンのない生活を想像できますか。" },
  { id: "v49", word: "realize", reading: "リアライズ", meaning: "気づく", example: "I didn't realize how important my family was.", exampleJa: "私は家族がどれほど大切かに気づいていませんでした。" },
  { id: "v50", word: "include", reading: "インクルード", meaning: "含む", example: "The price will include tax.", exampleJa: "その値段には税金が含まれます。" },
  { id: "v51", word: "exist", reading: "イグジスト", meaning: "存在する", example: "Many kinds of animals exist in this forest.", exampleJa: "この森には多くの種類の動物が存在します。" },
  { id: "v52", word: "international", reading: "インターナショナル", meaning: "国際的な", example: "She wants to work for an international company.", exampleJa: "彼女は国際的な会社で働きたいと思っています。" },
  { id: "v53", word: "culture", reading: "カルチャー", meaning: "文化", example: "It is interesting to learn about a different culture.", exampleJa: "異なる文化について学ぶことはおもしろいです。" },
  { id: "v54", word: "environment", reading: "インバイロメント", meaning: "環境", example: "We must work together to save the environment.", exampleJa: "私たちは環境を守るために協力しなければなりません。" },
  { id: "v55", word: "opportunity", reading: "オポチュニティ", meaning: "機会", example: "Studying abroad gave her a great opportunity.", exampleJa: "留学することは彼女に大きな機会を与えました。" },
];

export type GrammarQuestion = {
  id: string;
  prompt: string; // 日本語での問題文
  sentence: string; // ___ を含む英文
  sentenceJa: string; // 完成した英文の日本語訳
  answer: string; // 正解(小文字/大文字はゆるく判定)
  hint: string;
};

export const grammarList: GrammarQuestion[] = [
  // 受け身 (passive voice)
  {
    id: "g1",
    prompt: "( )の動詞を受け身の形にしよう",
    sentence: "This picture ___ (paint) by a famous artist 100 years ago.",
    sentenceJa: "この絵は100年前に有名な画家によって描かれました。",
    answer: "was painted",
    hint: "過去の受け身: was/were + 過去分詞",
  },
  {
    id: "g2",
    prompt: "( )の動詞を受け身の形にしよう",
    sentence: "These cars ___ (make) in Japan.",
    sentenceJa: "これらの車は日本で作られています。",
    answer: "are made",
    hint: "現在の受け身(複数): are + 過去分詞",
  },
  {
    id: "g3",
    prompt: "( )の動詞を受け身の形にしよう",
    sentence: "The window ___ (break) by the strong wind last night.",
    sentenceJa: "その窓はきのうの夜、強い風で割れました。",
    answer: "was broken",
    hint: "不規則動詞の過去分詞: break→broken",
  },
  {
    id: "g4",
    prompt: "( )の動詞を受け身の形にしよう",
    sentence: "This letter ___ (write) in English.",
    sentenceJa: "この手紙は英語で書かれています。",
    answer: "is written",
    hint: "現在の受け身: is + 過去分詞",
  },
  {
    id: "g5",
    prompt: "現在完了形の受け身を完成させよう",
    sentence: "The problem has already ___ (solve).",
    sentenceJa: "その問題はすでに解決されました。",
    answer: "been solved",
    hint: "現在完了の受け身: have/has been + 過去分詞",
  },
  {
    id: "g6",
    prompt: "未来の受け身を完成させよう",
    sentence: "A new bridge ___ (build) in this town next year.",
    sentenceJa: "この町に来年、新しい橋が建てられます。",
    answer: "will be built",
    hint: "未来の受け身: will be + 過去分詞",
  },
  {
    id: "g7",
    prompt: "( )の動詞を受け身の形にしよう",
    sentence: "This song ___ (sing) by many people around the world.",
    sentenceJa: "この歌は世界中の多くの人に歌われています。",
    answer: "is sung",
    hint: "sing の過去分詞は sung",
  },
  {
    id: "g8",
    prompt: "( )の動詞を受け身の形にしよう",
    sentence: "These photos ___ (take) by my sister last summer.",
    sentenceJa: "これらの写真は去年の夏、私の姉(妹)によって撮られました。",
    answer: "were taken",
    hint: "take の過去分詞は taken",
  },
  // 現在完了・現在完了進行形
  {
    id: "g9",
    prompt: "現在完了形(継続)の文を完成させよう",
    sentence: "I ___ (live) in Tokyo for ten years.",
    sentenceJa: "私は10年間東京に住んでいます。",
    answer: "have lived",
    hint: "for+期間 → 継続用法",
  },
  {
    id: "g10",
    prompt: "現在完了形(継続)の文を完成させよう",
    sentence: "She ___ (know) him since we were children.",
    sentenceJa: "彼女は私たちが子どものころから彼を知っています。",
    answer: "has known",
    hint: "since+起点 → 継続用法",
  },
  {
    id: "g11",
    prompt: "現在完了形(経験)の文を完成させよう",
    sentence: "I ___ (be) to Okinawa three times.",
    sentenceJa: "私は沖縄に3回行ったことがあります。",
    answer: "have been",
    hint: "経験用法: have been to 〜",
  },
  {
    id: "g12",
    prompt: "現在完了形(経験・否定)の文を完成させよう",
    sentence: "He has never ___ (eat) natto before.",
    sentenceJa: "彼は今までに一度も納豆を食べたことがありません。",
    answer: "eaten",
    hint: "eat の過去分詞は eaten",
  },
  {
    id: "g13",
    prompt: "現在完了進行形の文を完成させよう",
    sentence: "We ___ (study) English for two hours now.",
    sentenceJa: "私たちは今2時間ずっと英語を勉強しています。",
    answer: "have been studying",
    hint: "現在完了進行形: have been + ing",
  },
  {
    id: "g14",
    prompt: "現在完了進行形の文を完成させよう",
    sentence: "It ___ (rain) since this morning.",
    sentenceJa: "今朝からずっと雨が降っています。",
    answer: "has been raining",
    hint: "ずっと雨が降り続けている→現在完了進行形",
  },
  {
    id: "g15",
    prompt: "現在完了形(完了)の疑問文を完成させよう",
    sentence: "Have you ___ (finish) your homework yet?",
    sentenceJa: "あなたはもう宿題を終えましたか。",
    answer: "finished",
    hint: "yetを使う疑問文は過去分詞のみでOK",
  },
  {
    id: "g16",
    prompt: "現在完了形(完了)の文を完成させよう",
    sentence: "I have just ___ (finish) cleaning my room.",
    sentenceJa: "私はちょうど部屋の掃除を終えたところです。",
    answer: "finished",
    hint: "have just + 過去分詞: ちょうど〜したところ",
  },
  {
    id: "g17",
    prompt: "現在完了進行形の疑問文を完成させよう",
    sentence: "How long have you ___ (wait) here?",
    sentenceJa: "あなたはどのくらいここで待っているのですか。",
    answer: "been waiting",
    hint: "現在完了進行形: have been + ing",
  },
  {
    id: "g18",
    prompt: "現在完了形(経験)の文を完成させよう",
    sentence: "This is the first time I ___ (visit) Kyoto.",
    sentenceJa: "これは私が京都を訪れるのは初めてです。",
    answer: "have visited",
    hint: "the first time + 現在完了(経験)",
  },
  // 不定詞の応用
  {
    id: "g19",
    prompt: "「It is ~ for 人 to ...」の形を完成させよう",
    sentence: "It is important ___ (study) every day.",
    sentenceJa: "毎日勉強することは大切です。",
    answer: "to study",
    hint: "It is ~ for 人 to ...の基本形",
  },
  {
    id: "g20",
    prompt: "「It is ~ for 人 to ...」の形を完成させよう",
    sentence: "It was difficult for him ___ (solve) the problem.",
    sentenceJa: "彼にとってその問題を解決することは難しかったです。",
    answer: "to solve",
    hint: "for 人 to ~: 〜にとって",
  },
  {
    id: "g21",
    prompt: "「too ~ to ...」の形を完成させよう",
    sentence: "This question is too difficult ___ (answer).",
    sentenceJa: "この問題は難しすぎて答えられません。",
    answer: "to answer",
    hint: "too ~ to ...: 〜すぎて…できない",
  },
  {
    id: "g22",
    prompt: "「~ enough to ...」の形を完成させよう",
    sentence: "She is old enough ___ (drive) a car.",
    sentenceJa: "彼女は車を運転できるくらいの年齢です。",
    answer: "to drive",
    hint: "形容詞 + enough to ...: 〜するのに十分…",
  },
  {
    id: "g23",
    prompt: "「疑問詞+to不定詞」の形を完成させよう",
    sentence: "I don't know ___ (say) to her.",
    sentenceJa: "私は彼女に何と言えばよいかわかりません。",
    answer: "what to say",
    hint: "「何を言うべきか」= what to say",
  },
  {
    id: "g24",
    prompt: "「疑問詞+to不定詞」の形を完成させよう",
    sentence: "Please tell me ___ (use) this machine.",
    sentenceJa: "この機械の使い方を教えてください。",
    answer: "how to use",
    hint: "「使い方」= how to use",
  },
  {
    id: "g25",
    prompt: "「tell 人 to ~」の形を完成させよう",
    sentence: "My mother told me ___ (clean) my room.",
    sentenceJa: "母は私に部屋を掃除するように言いました。",
    answer: "to clean",
    hint: "tell + 人 + to + 動詞の原形",
  },
  {
    id: "g26",
    prompt: "「ask 人 to ~」の形を完成させよう",
    sentence: "He asked me ___ (help) him.",
    sentenceJa: "彼は私に手伝ってくれるように頼みました。",
    answer: "to help",
    hint: "ask + 人 + to + 動詞の原形",
  },
  // 関係代名詞
  {
    id: "g27",
    prompt: "人を説明する関係代名詞を完成させよう",
    sentence: "I have a friend ___ (who) can speak three languages.",
    sentenceJa: "私には3つの言語を話せる友人がいます。",
    answer: "who",
    hint: "人を説明する主格の関係代名詞",
  },
  {
    id: "g28",
    prompt: "ものを説明する関係代名詞を完成させよう",
    sentence: "This is the book ___ (which) I bought yesterday.",
    sentenceJa: "これは私がきのう買った本です。",
    answer: "which",
    hint: "ものを説明する目的格の関係代名詞",
  },
  {
    id: "g29",
    prompt: "人を説明する関係代名詞を完成させよう",
    sentence: "The girl ___ (who) is singing on the stage is my sister.",
    sentenceJa: "ステージで歌っている女の子は私の姉(妹)です。",
    answer: "who",
    hint: "主格の関係代名詞(人)",
  },
  {
    id: "g30",
    prompt: "who/whichの代わりに使える関係代名詞を完成させよう",
    sentence: "I like the movie ___ (that) we watched last night.",
    sentenceJa: "私は私たちが昨夜見た映画が好きです。",
    answer: "that",
    hint: "who/whichの代わりに使えるthat",
  },
  {
    id: "g31",
    prompt: "ものを説明する関係代名詞を完成させよう",
    sentence: "The bag ___ (which) is on the desk is mine.",
    sentenceJa: "机の上にあるかばんは私のものです。",
    answer: "which",
    hint: "主格の関係代名詞(もの)",
  },
  {
    id: "g32",
    prompt: "人を説明する関係代名詞を完成させよう",
    sentence: "He is the man ___ (who) helped me yesterday.",
    sentenceJa: "彼はきのう私を助けてくれた男性です。",
    answer: "who",
    hint: "主格の関係代名詞(人)",
  },
  {
    id: "g33",
    prompt: "目的格の関係代名詞を完成させよう",
    sentence: "This is the house ___ (that) my grandfather built.",
    sentenceJa: "これは私の祖父が建てた家です。",
    answer: "that",
    hint: "目的格の関係代名詞",
  },
  {
    id: "g34",
    prompt: "ものを説明する関係代名詞を完成させよう",
    sentence: "The music ___ (which) she likes is very popular.",
    sentenceJa: "彼女が好きな音楽はとても人気があります。",
    answer: "which",
    hint: "目的格の関係代名詞(もの)",
  },
  // 分詞の後置修飾
  {
    id: "g35",
    prompt: "( )の動詞を分詞にして名詞を修飾しよう",
    sentence: "The boy ___ (play) tennis over there is my brother.",
    sentenceJa: "あそこでテニスをしている男の子は私の兄(弟)です。",
    answer: "playing",
    hint: "現在分詞(〜している)が名詞を後ろから修飾",
  },
  {
    id: "g36",
    prompt: "( )の動詞を分詞にして名詞を修飾しよう",
    sentence: "Look at the mountain ___ (cover) with snow.",
    sentenceJa: "雪でおおわれた山を見てください。",
    answer: "covered",
    hint: "過去分詞(〜される)が名詞を後ろから修飾",
  },
  {
    id: "g37",
    prompt: "( )の動詞を分詞にして名詞を修飾しよう",
    sentence: "The language ___ (speak) in Brazil is Portuguese.",
    sentenceJa: "ブラジルで話されている言語はポルトガル語です。",
    answer: "spoken",
    hint: "受け身の意味を持つ過去分詞",
  },
  {
    id: "g38",
    prompt: "( )の動詞を分詞にして名詞を修飾しよう",
    sentence: "Do you know the girl ___ (stand) by the door?",
    sentenceJa: "ドアのそばに立っている女の子を知っていますか。",
    answer: "standing",
    hint: "現在分詞: 〜している",
  },
  {
    id: "g39",
    prompt: "( )の動詞を分詞にして名詞を修飾しよう",
    sentence: "This is a picture ___ (take) in Kyoto.",
    sentenceJa: "これは京都で撮られた写真です。",
    answer: "taken",
    hint: "過去分詞: 〜された",
  },
  {
    id: "g40",
    prompt: "( )の動詞を分詞にして名詞を修飾しよう",
    sentence: "The letter ___ (write) in French was from my pen pal.",
    sentenceJa: "フランス語で書かれたその手紙は私のペンパルからでした。",
    answer: "written",
    hint: "write の過去分詞は written",
  },
  // 間接疑問文
  {
    id: "g41",
    prompt: "「Where does he live?」を I don't know に続く形にして文を完成させよう",
    sentence: "I don't know ___.",
    sentenceJa: "私は彼がどこに住んでいるか知りません。",
    answer: "where he lives",
    hint: "疑問詞のあとは主語+動詞の語順(3単現に注意)",
  },
  {
    id: "g42",
    prompt: "「What does this mean?」を Do you know に続く形にして文を完成させよう",
    sentence: "Do you know ___?",
    sentenceJa: "これが何を意味するか知っていますか。",
    answer: "what this means",
    hint: "疑問詞+主語+動詞の順番",
  },
  {
    id: "g43",
    prompt: "「Who is that?」を Please tell me に続く形にして文を完成させよう",
    sentence: "Please tell me ___.",
    sentenceJa: "あれが誰なのか私に教えてください。",
    answer: "who that is",
    hint: "be動詞の位置に注意",
  },
  {
    id: "g44",
    prompt: "「Why is she sad?」を I want to know に続く形にして文を完成させよう",
    sentence: "I want to know ___.",
    sentenceJa: "私はなぜ彼女が悲しいのか知りたいです。",
    answer: "why she is sad",
    hint: "疑問詞+主語+動詞の順番",
  },
  {
    id: "g45",
    prompt: "「When does the train leave?」を Could you tell me に続く形にして文を完成させよう",
    sentence: "Could you tell me ___?",
    sentenceJa: "その電車がいつ出発するか教えていただけますか。",
    answer: "when the train leaves",
    hint: "3人称単数現在のsを忘れずに",
  },
  // 使役動詞・知覚動詞
  {
    id: "g46",
    prompt: "「make+人+動詞の原形」の形を完成させよう",
    sentence: "My mother ___ (make) me clean my room.",
    sentenceJa: "母は私に部屋を掃除させました。",
    answer: "made",
    hint: "make+人+動詞の原形: 〜させる",
  },
  {
    id: "g47",
    prompt: "「let+人+動詞の原形」の形を完成させよう",
    sentence: "Please ___ (let) me know your idea.",
    sentenceJa: "あなたの考えを私に知らせてください。",
    answer: "let",
    hint: "let+人+動詞の原形: 〜させてあげる",
  },
  {
    id: "g48",
    prompt: "知覚動詞see+人+動詞の原形の形を完成させよう",
    sentence: "I saw him ___ (cross) the street.",
    sentenceJa: "私は彼が道を渡るのを見ました。",
    answer: "cross",
    hint: "知覚動詞see+人+動詞の原形",
  },
  {
    id: "g49",
    prompt: "知覚動詞hear+人+ingの形を完成させよう",
    sentence: "She heard someone ___ (sing) in the next room.",
    sentenceJa: "彼女はとなりの部屋で誰かが歌っているのを聞きました。",
    answer: "singing",
    hint: "知覚動詞hear+人+ing(〜しているところを)",
  },
  {
    id: "g50",
    prompt: "「help+人+動詞の原形」の形を完成させよう",
    sentence: "Can you ___ (help) me carry this bag?",
    sentenceJa: "このかばんを運ぶのを手伝ってくれますか。",
    answer: "help",
    hint: "help+人+動詞の原形",
  },
  // so~that / 比較の応用
  {
    id: "g51",
    prompt: "「so ~ that ...」の形を完成させよう",
    sentence: "This box is ___ (so) heavy that I can't lift it.",
    sentenceJa: "この箱はとても重いので私は持ち上げられません。",
    answer: "so",
    hint: "so ~ that ...: とても〜なので…",
  },
  {
    id: "g52",
    prompt: "「such ~ that ...」の形を完成させよう",
    sentence: "It was ___ (such) a difficult question that nobody could answer it.",
    sentenceJa: "それはとても難しい問題だったので誰も答えられませんでした。",
    answer: "such",
    hint: "such a/an+形容詞+名詞+that ...",
  },
  {
    id: "g53",
    prompt: "「as ~ as possible」の形を完成させよう",
    sentence: "Please walk as quietly ___ (as) possible.",
    sentenceJa: "できるだけ静かに歩いてください。",
    answer: "as",
    hint: "as ~ as possible: できるだけ〜",
  },
  {
    id: "g54",
    prompt: "「the+比較級, the+比較級」の形を完成させよう",
    sentence: "The more you practice, ___ (good) you will become.",
    sentenceJa: "練習すればするほど、あなたは上手になるでしょう。",
    answer: "the better",
    hint: "the+比較級, the+比較級: 〜すればするほど…",
  },
  {
    id: "g55",
    prompt: "最上級を強調する形を完成させよう",
    sentence: "This is by far ___ (interesting) book I have ever read.",
    sentenceJa: "これは私が今まで読んだ中で断然おもしろい本です。",
    answer: "the most interesting",
    hint: "最上級の強調: by far the + 最上級",
  },
];
